import type { Metadata } from "next";
import { NextIntlClientProvider, useLocale, useMessages } from "next-intl";

import { Roboto, Roboto_Condensed, Scada } from "next/font/google";

import { ChildrenProps, LocalizationProps } from "@/types";

import { WidthToast } from "./with-toast";

import "@/styles/globals.css";

const roboto = Roboto({
    weight: ["400", "500", "700"],
    style: ["normal", "italic"],
    variable: "--font-roboto",
    subsets: ["latin", "cyrillic"],
    display: "swap",
});

const robotoCondensed = Roboto_Condensed({
    weight: ["400", "500", "700"],
    style: ["normal", "italic"],
    variable: "--font-robotoCondensed",
    subsets: ["latin", "cyrillic"],
    display: "swap",
});

const scada = Scada({
    weight: ["400", "700"],
    style: ["normal", "italic"],
    variable: "--font-scada",
    subsets: ["latin", "cyrillic"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: ChildrenProps<LocalizationProps>) {
    const locale = useLocale();
    const messages = useMessages();

    return (
        <html
            lang={locale}
            suppressHydrationWarning
            className="scroll-smooth"
        >
            <body
                suppressHydrationWarning
                className={`${roboto.variable} ${robotoCondensed.variable} ${scada.variable}`}
            >
                <NextIntlClientProvider messages={messages}>
                    <WidthToast>{children}</WidthToast>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
